// <auto-generated />
using System;
using AutoMapperApp.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoMapperApp.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251018133759_AddMoreSeedData")]
    partial class AddMoreSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("AutoMapperApp.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2025, 10, 18, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Monitor UltraWide",
                            Price = 1450.50m
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2025, 10, 18, 10, 5, 0, 0, DateTimeKind.Unspecified),
                            Name = "Teclado Mecânico",
                            Price = 250.50m
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2025, 10, 18, 10, 10, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mouse Gamer",
                            Price = 120.00m
                        },
                        new
                        {
                            Id = 4,
                            CreationDate = new DateTime(2025, 10, 18, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            Name = "Headset Bluetooth",
                            Price = 300.00m
                        },
                        new
                        {
                            Id = 5,
                            CreationDate = new DateTime(2025, 10, 18, 10, 20, 0, 0, DateTimeKind.Unspecified),
                            Name = "Webcam 4K",
                            Price = 450.00m
                        },
                        new
                        {
                            Id = 6,
                            CreationDate = new DateTime(2025, 10, 18, 10, 25, 0, 0, DateTimeKind.Unspecified),
                            Name = "SSD NVMe 1TB",
                            Price = 550.00m
                        },
                        new
                        {
                            Id = 7,
                            CreationDate = new DateTime(2025, 10, 18, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Name = "Placa de Vídeo RTX 4070",
                            Price = 4500.00m
                        },
                        new
                        {
                            Id = 8,
                            CreationDate = new DateTime(2025, 10, 18, 10, 35, 0, 0, DateTimeKind.Unspecified),
                            Name = "Processador Intel i7",
                            Price = 2200.00m
                        },
                        new
                        {
                            Id = 9,
                            CreationDate = new DateTime(2025, 10, 18, 10, 40, 0, 0, DateTimeKind.Unspecified),
                            Name = "Memória RAM 16GB",
                            Price = 350.00m
                        },
                        new
                        {
                            Id = 10,
                            CreationDate = new DateTime(2025, 10, 18, 10, 45, 0, 0, DateTimeKind.Unspecified),
                            Name = "Gabinete Gamer",
                            Price = 600.00m
                        },
                        new
                        {
                            Id = 11,
                            CreationDate = new DateTime(2025, 10, 18, 10, 50, 0, 0, DateTimeKind.Unspecified),
                            Name = "Fonte ATX 750W",
                            Price = 400.00m
                        },
                        new
                        {
                            Id = 12,
                            CreationDate = new DateTime(2025, 10, 18, 10, 55, 0, 0, DateTimeKind.Unspecified),
                            Name = "Cadeira Gamer",
                            Price = 900.00m
                        },
                        new
                        {
                            Id = 13,
                            CreationDate = new DateTime(2025, 10, 18, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mesa para PC",
                            Price = 700.00m
                        },
                        new
                        {
                            Id = 14,
                            CreationDate = new DateTime(2025, 10, 18, 11, 5, 0, 0, DateTimeKind.Unspecified),
                            Name = "Microfone Condensador",
                            Price = 280.00m
                        },
                        new
                        {
                            Id = 15,
                            CreationDate = new DateTime(2025, 10, 18, 11, 10, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ring Light",
                            Price = 150.00m
                        },
                        new
                        {
                            Id = 16,
                            CreationDate = new DateTime(2025, 10, 18, 11, 15, 0, 0, DateTimeKind.Unspecified),
                            Name = "Controle Xbox",
                            Price = 320.00m
                        },
                        new
                        {
                            Id = 17,
                            CreationDate = new DateTime(2025, 10, 18, 11, 20, 0, 0, DateTimeKind.Unspecified),
                            Name = "Volante Logitech",
                            Price = 1200.00m
                        },
                        new
                        {
                            Id = 18,
                            CreationDate = new DateTime(2025, 10, 18, 11, 25, 0, 0, DateTimeKind.Unspecified),
                            Name = "Joystick Arcade",
                            Price = 480.00m
                        },
                        new
                        {
                            Id = 19,
                            CreationDate = new DateTime(2025, 10, 18, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            Name = "Óculos VR",
                            Price = 2500.00m
                        },
                        new
                        {
                            Id = 20,
                            CreationDate = new DateTime(2025, 10, 18, 11, 35, 0, 0, DateTimeKind.Unspecified),
                            Name = "Drone DJI Mini",
                            Price = 1800.00m
                        },
                        new
                        {
                            Id = 21,
                            CreationDate = new DateTime(2025, 10, 18, 11, 40, 0, 0, DateTimeKind.Unspecified),
                            Name = "Câmera Mirrorless",
                            Price = 3200.00m
                        },
                        new
                        {
                            Id = 22,
                            CreationDate = new DateTime(2025, 10, 18, 11, 45, 0, 0, DateTimeKind.Unspecified),
                            Name = "Lente 50mm",
                            Price = 800.00m
                        },
                        new
                        {
                            Id = 23,
                            CreationDate = new DateTime(2025, 10, 18, 11, 50, 0, 0, DateTimeKind.Unspecified),
                            Name = "Tripé Profissional",
                            Price = 200.00m
                        },
                        new
                        {
                            Id = 24,
                            CreationDate = new DateTime(2025, 10, 18, 11, 55, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mochila para Câmera",
                            Price = 180.00m
                        },
                        new
                        {
                            Id = 25,
                            CreationDate = new DateTime(2025, 10, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Cartão SD 128GB",
                            Price = 90.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
