// <auto-generated />
using System;
using AutoMapperApp.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoMapperApp.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251018130959_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("AutoMapperApp.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2025, 10, 18, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Monitor UltraWide",
                            Price = 1450.50m
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2025, 10, 18, 10, 5, 0, 0, DateTimeKind.Unspecified),
                            Name = "Teclado Mecânico",
                            Price = 250.50m
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2025, 10, 18, 10, 10, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mouse Gamer",
                            Price = 120.00m
                        },
                        new
                        {
                            Id = 4,
                            CreationDate = new DateTime(2025, 10, 18, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            Name = "Headset Bluetooth",
                            Price = 300.00m
                        },
                        new
                        {
                            Id = 5,
                            CreationDate = new DateTime(2025, 10, 18, 10, 20, 0, 0, DateTimeKind.Unspecified),
                            Name = "Webcam 4K",
                            Price = 450.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
